# Generated by Django 4.0.6 on 2022-07-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField()),
                ('image_url', models.TextField()),
                ('original_price', models.IntegerField()),
                ('current_price', models.IntegerField()),
                ('item_description', models.TextField()),
            ],
        ),
    ]
